# Generated by Django 5.2.16 on 2026-07-24 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('labs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('asset_tag', models.CharField(max_length=100, unique=True)),
                ('expected_quantity', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Missing', 'Missing')], default='Available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='labs.lab')),
            ],
        ),
    ]
