# Generated by Django 5.2.16 on 2026-07-26 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='brand',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='camera',
            name='fps',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='camera',
            name='ip_address',
            field=models.CharField(blank=True, default='192.168.1.100', max_length=100),
        ),
        migrations.AddField(
            model_name='camera',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='camera',
            name='model_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='camera',
            name='password',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='camera',
            name='resolution',
            field=models.CharField(blank=True, default='1920x1080', max_length=50),
        ),
        migrations.AddField(
            model_name='camera',
            name='rtsp_url',
            field=models.CharField(blank=True, default='rtsp://192.168.1.100:554/stream', max_length=255),
        ),
        migrations.AddField(
            model_name='camera',
            name='username',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='camera',
            name='location',
            field=models.CharField(blank=True, default='Overhead Ceiling View', max_length=200),
        ),
        migrations.AlterField(
            model_name='camera',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='camera',
            name='status',
            field=models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline'), ('Connecting', 'Connecting'), ('Error', 'Error')], default='Online', max_length=20),
        ),
    ]
