# Generated by Django 5.2.16 on 2026-07-24 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('cameras', '0001_initial'),
        ('labs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_quantity', models.PositiveIntegerField()),
                ('detected_quantity', models.PositiveIntegerField()),
                ('confidence', models.FloatField()),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Investigating', 'Investigating'), ('Resolved', 'Resolved')], default='Open', max_length=20)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.asset')),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cameras.camera')),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labs.lab')),
            ],
        ),
    ]
