# Generated by Django 5.2.16 on 2026-07-24 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('cameras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_image', models.ImageField(upload_to='reference_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_profiles', to='cameras.camera')),
            ],
        ),
        migrations.CreateModel(
            name='ReferenceAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detected_quantity', models.PositiveIntegerField()),
                ('confidence', models.FloatField()),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.asset')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='reference.referenceprofile')),
            ],
        ),
    ]
