# Generated by Django 5.2.16 on 2026-07-26 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
        ('cameras', '0002_camera_brand_camera_fps_camera_ip_address_and_more'),
        ('labs', '0001_initial'),
        ('reference', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='referenceasset',
            name='asset_name',
            field=models.CharField(blank=True, default='Monitor', max_length=100),
        ),
        migrations.AddField(
            model_name='referenceasset',
            name='category',
            field=models.CharField(blank=True, default='computer', max_length=50),
        ),
        migrations.AddField(
            model_name='referenceprofile',
            name='created_by',
            field=models.CharField(default='Dr. Tabraiz Shams', max_length=100),
        ),
        migrations.AddField(
            model_name='referenceprofile',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='referenceprofile',
            name='lab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reference_profiles', to='labs.lab'),
        ),
        migrations.AddField(
            model_name='referenceprofile',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='referenceprofile',
            name='name',
            field=models.CharField(default='Standard Baseline Profile', max_length=100),
        ),
        migrations.AlterField(
            model_name='referenceasset',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.asset'),
        ),
        migrations.AlterField(
            model_name='referenceasset',
            name='confidence',
            field=models.FloatField(default=0.95),
        ),
        migrations.AlterField(
            model_name='referenceasset',
            name='detected_quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='referenceprofile',
            name='camera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reference_profiles', to='cameras.camera'),
        ),
        migrations.AlterField(
            model_name='referenceprofile',
            name='reference_image',
            field=models.ImageField(blank=True, null=True, upload_to='reference_images/'),
        ),
    ]
