# Generated by Django 5.2.16 on 2026-07-26 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('labs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, max_length=50, unique=True)),
                ('instructor_name', models.CharField(max_length=100)),
                ('course_name', models.CharField(max_length=100)),
                ('course_code', models.CharField(blank=True, default='', max_length=50)),
                ('session_topic', models.CharField(max_length=200)),
                ('planned_duration', models.PositiveIntegerField(default=120)),
                ('status', models.CharField(choices=[('Created', 'Created'), ('Active', 'Active'), ('Paused', 'Paused'), ('Completed', 'Completed')], default='Active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='labs.lab')),
            ],
        ),
    ]
