# Generated by Django 5.2.16 on 2026-07-24 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='evidence/images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='evidence/videos/')),
                ('confidence', models.FloatField()),
                ('captured_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='incidents.incident')),
            ],
        ),
    ]
